import type {
  BindingTable,
  CoBindingTable,
  Command,
  KeyboardLayout,
  MouseButton,
} from '@/types';
import { ALL_LAYERS } from '@/types';
import { layerDisplayName, layerPrefix } from './layers';
import { stripModePrefix } from '@/lib/binding-keys';

export interface ExportInput {
  layout: KeyboardLayout;
  bindings: BindingTable;
  /**
   * Optional sidecar of additional commands per (layer, keyId) — emitted as
   * extra `bind` lines after the primary, so BAR's double-binds (e.g.
   * `manualfire` + `manuallaunch` on `sc_d`) round-trip faithfully.
   */
  coBindings?: CoBindingTable;
  mouseButtons: readonly MouseButton[];
  /** All commands available — built-in + custom — keyed by id. */
  commandsById: ReadonlyMap<string, Command>;
  /** ISO timestamp for the header line; pass to keep output deterministic in tests. */
  timestamp?: string;
  /** Human-readable name of the BAR preset this keymap was last derived from. */
  sourcePresetName?: string | null;
}

interface BindableTarget {
  /** physical-key id or mouse id (for sort + lookup) */
  id: string;
  /** uikeys.txt token */
  bindName: string;
  /** sort key: smaller = earlier in output */
  order: number;
}

function physicalOrder(layout: KeyboardLayout): Map<string, number> {
  const sorted = [...layout.keys].sort((a, b) => {
    if (a.y !== b.y) return a.y - b.y;
    return a.x - b.x;
  });
  return new Map(sorted.map((k, i) => [k.id, i] as const));
}

function collectTargets(
  layout: KeyboardLayout,
  mouseButtons: readonly MouseButton[],
): Map<string, BindableTarget> {
  const order = physicalOrder(layout);
  const out = new Map<string, BindableTarget>();
  for (const k of layout.keys) {
    if (k.bindName == null) continue;
    out.set(k.id, {
      id: k.id,
      bindName: k.bindName,
      order: order.get(k.id) ?? 0,
    });
  }
  // Mouse buttons go after all keys, in id order (mouse1, mouse2, …).
  const keyCount = layout.keys.length;
  mouseButtons.forEach((m, i) => {
    out.set(m.id, {
      id: m.id,
      bindName: m.bindName,
      order: keyCount + i,
    });
  });
  return out;
}

export function buildUikeysTxt(input: ExportInput): string {
  const { layout, bindings, coBindings, mouseButtons, commandsById, timestamp, sourcePresetName } = input;
  const targets = collectTargets(layout, mouseButtons);

  const ts = timestamp ?? new Date().toISOString();
  const lines: string[] = [
    '// uikeys.txt — generated by BAR keymap editor',
    `// Layout: ${layout.name}`,
    ...(sourcePresetName ? [`// Derived from BAR preset: ${sourcePresetName}`] : []),
    `// Generated: ${ts}`,
    '',
  ];

  for (const layer of ALL_LAYERS) {
    const layerBindings = bindings[layer] ?? {};
    const entries = Object.entries(layerBindings).filter(([keyId, cmdId]) => {
      if (!cmdId) return false;
      const baseKeyId = stripModePrefix(keyId);
      if (!targets.has(baseKeyId)) return false;
      return commandsById.has(cmdId);
    });
    if (entries.length === 0) continue;

    lines.push(`// ${layerDisplayName(layer)}`);
    entries.sort(([a], [b]) => {
      const oa = targets.get(stripModePrefix(a))?.order ?? 0;
      const ob = targets.get(stripModePrefix(b))?.order ?? 0;
      return oa - ob;
    });

    const prefix = layerPrefix(layer);
    const coLayer = coBindings?.[layer] ?? {};
    for (const [keyId, cmdId] of entries) {
      const baseKeyId = stripModePrefix(keyId);
      const target = targets.get(baseKeyId);
      const cmd = commandsById.get(cmdId);
      if (!target || !cmd) continue;
      // Space doubles as BAR's Meta modifier, so pressing Space alone is seen
      // by the engine as `Meta+space`. A plain `bind space …` therefore never
      // matches at runtime — BAR's own configs all use `Any+space`.
      const effectivePrefix = layer === '' && target.bindName === 'space' ? 'Any+' : prefix;
      // Primary binding first — this is the one shown in the editor UI.
      lines.push(`bind ${effectivePrefix}${target.bindName} ${cmd.uikeysCommand}`);
      // Then any co-bindings — preserves BAR's double-bind pattern (e.g.
      // sc_d → manualfire + manuallaunch) without making the player choose.
      const cos = coLayer[keyId];
      if (cos) {
        for (const coId of cos) {
          if (coId === cmdId) continue;
          const coCmd = commandsById.get(coId);
          if (!coCmd) continue;
          lines.push(`bind ${effectivePrefix}${target.bindName} ${coCmd.uikeysCommand}`);
        }
      }
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}
