#!/usr/bin/env node
/**
 * Scrape authoritative constants and tables from the Recoil engine source
 * (https://github.com/beyond-all-reason/RecoilEngine) and write them to
 * `src/data/generated/engine.ts`.
 *
 * Rationale: things like `NUM_BUTTONS`, `ACTION_BUTTON_MIN`, and the engine's
 * `defaultBindings[]` table belong to the engine, not to this editor. Pinning
 * them via a scraper keeps the editor in lockstep with what BAR actually
 * loads, instead of hand-maintaining a copy.
 *
 * Run with `node scripts/scrape-engine.mjs`. The output is checked in so
 * dev/CI don't need network access — re-run to refresh.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'src/data/generated/engine.ts');
const RAW = 'https://raw.githubusercontent.com/beyond-all-reason/RecoilEngine/master';

const SOURCES = {
  mouseHandler: `${RAW}/rts/Game/UI/MouseHandler.h`,
  keyBindings: `${RAW}/rts/Game/UI/KeyBindings.cpp`,
  keyCodes: `${RAW}/rts/Game/UI/KeyCodes.cpp`,
};

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch ${url} failed: ${res.status}`);
  return res.text();
}

function matchInt(src, name) {
  const re = new RegExp(`${name}\\s*=\\s*(\\d+)`);
  const m = src.match(re);
  if (!m) throw new Error(`Could not find ${name} in source`);
  return Number(m[1]);
}

/**
 * Extracts the `defaultBindings[]` initializer-list from KeyBindings.cpp.
 * The C++ shape:
 *   static const DefaultBinding defaultBindings[] = {
 *     {            "esc", "quitmessage" },
 *     {      "Shift+esc", "quitmenu"    },
 *     ...
 *   };
 * We parse pairs of double-quoted strings, ignoring comments and whitespace.
 */
function parseDefaultBindings(src) {
  const startIdx = src.indexOf('defaultBindings[]');
  if (startIdx < 0) throw new Error('defaultBindings[] not found');
  // Locate the opening brace of the initializer list.
  const openIdx = src.indexOf('{', startIdx);
  if (openIdx < 0) throw new Error('Initializer list `{` not found');
  // Walk to the matching outer `};` — naive but works because nested braces
  // are balanced one-deep per entry.
  let depth = 0;
  let endIdx = -1;
  for (let i = openIdx; i < src.length; i++) {
    const ch = src[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) {
        endIdx = i;
        break;
      }
    }
  }
  if (endIdx < 0) throw new Error('Could not find end of defaultBindings[]');
  const body = src.slice(openIdx + 1, endIdx);

  // Strip C-style comments.
  const noBlockComments = body.replace(/\/\*[\s\S]*?\*\//g, '');
  const noLineComments = noBlockComments.replace(/\/\/[^\n]*/g, '');

  // Each entry: `{ "key", "action" }` — capture in order.
  const entryRe = /\{\s*"((?:\\.|[^"\\])*)"\s*,\s*"((?:\\.|[^"\\])*)"\s*\}/g;
  const out = [];
  let m;
  while ((m = entryRe.exec(noLineComments)) !== null) {
    out.push({ key: m[1], action: m[2] });
  }
  if (out.length === 0) throw new Error('Parsed zero entries from defaultBindings[]');
  return out;
}

/**
 * Pull every `RegisterAction("foo")` from KeyBindings.cpp — the engine
 * vocabulary of bindable actions. Comments are stripped first so commented-
 * out registrations don't leak in.
 */
function parseRegisteredActions(src) {
  const noBlock = src.replace(/\/\*[\s\S]*?\*\//g, '');
  const noLine = noBlock.replace(/\/\/[^\n]*/g, '');
  const re = /RegisterAction\s*\(\s*"([^"\\]+)"\s*\)/g;
  const seen = new Set();
  let m;
  while ((m = re.exec(noLine)) !== null) seen.add(m[1]);
  return [...seen].sort();
}

async function main() {
  const [mouseSrc, kbSrc, kcSrc] = await Promise.all([
    fetchText(SOURCES.mouseHandler),
    fetchText(SOURCES.keyBindings),
    fetchText(SOURCES.keyCodes),
  ]);

  const NUM_BUTTONS = matchInt(mouseSrc, 'NUM_BUTTONS');
  const ACTION_BUTTON_MIN = matchInt(mouseSrc, 'ACTION_BUTTON_MIN');
  const defaultBindings = parseDefaultBindings(kbSrc);
  const registeredActions = parseRegisteredActions(kbSrc);

  // Sanity-check that KeyCodes.cpp still registers mouseN tokens at the
  // expected range — if Recoil refactors, fail loudly.
  if (!/mouse"\s*\+\s*IntToString\(i\)/.test(kcSrc)) {
    console.warn(
      '! KeyCodes.cpp no longer matches the expected `mouse" + IntToString(i)` ' +
        'registration pattern. Verify mouseN token semantics before trusting the scrape.',
    );
  }

  mkdirSync(dirname(OUT), { recursive: true });

  const banner = `/**
 * GENERATED by scripts/scrape-engine.mjs — do not edit by hand.
 *
 * Source: github.com/beyond-all-reason/RecoilEngine@master
 *   - rts/Game/UI/MouseHandler.h     (NUM_BUTTONS, ACTION_BUTTON_MIN)
 *   - rts/Game/UI/KeyBindings.cpp    (defaultBindings[], RegisterAction calls)
 *
 * Scraped at: ${new Date().toISOString()}
 *
 * Re-run \`node scripts/scrape-engine.mjs\` to refresh.
 */`;

  const body = `${banner}

/** Highest bindable mouseN token (from MouseHandler.h \`NUM_BUTTONS\`). */
export const NUM_BUTTONS = ${NUM_BUTTONS} as const;

/**
 * Lowest bindable mouseN token (from MouseHandler.h \`ACTION_BUTTON_MIN\`).
 * The engine registers \`mouse\${ACTION_BUTTON_MIN}\` … \`mouse\${NUM_BUTTONS}\`
 * — anything below this (notably \`mouse1\`) is silently un-bindable.
 */
export const ACTION_BUTTON_MIN = ${ACTION_BUTTON_MIN} as const;

export interface EngineDefaultBinding {
  /** Raw key string from the engine table (e.g. "Any+pause", "c", "Ctrl+Shift+esc"). */
  readonly key: string;
  /** Raw action string from the engine table (e.g. "pause", "controlunit"). */
  readonly action: string;
}

/**
 * Engine \`defaultBindings[]\` table. Loaded BEFORE any \`uikeys.txt\` via
 * \`KeyBindings::LoadDefaults()\`. Player \`uikeys.txt\` bindings ADD to these
 * (BAR's \`Bind()\` is additive, not replacement) — to actually replace a
 * default the player must explicitly \`unbind\` or \`unbindaction\`.
 */
export const ENGINE_DEFAULT_BINDINGS: readonly EngineDefaultBinding[] = ${JSON.stringify(
    defaultBindings,
    null,
    2,
  )};

/**
 * Every action string the engine registers via \`RegisterAction("…")\`.
 * Useful for offering the player the full vocabulary of bindable actions
 * (not just the BAR-game commands).
 */
export const ENGINE_REGISTERED_ACTIONS: readonly string[] = ${JSON.stringify(
    registeredActions,
    null,
    2,
  )};
`;

  writeFileSync(OUT, body);
  console.log(`✓ wrote ${OUT}`);
  console.log(`  NUM_BUTTONS = ${NUM_BUTTONS}`);
  console.log(`  ACTION_BUTTON_MIN = ${ACTION_BUTTON_MIN}`);
  console.log(`  defaultBindings[] entries: ${defaultBindings.length}`);
  console.log(`  RegisterAction() entries: ${registeredActions.length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
